In [1]:
pip install numpy

  Using cached numpy-2.4.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Using cached numpy-2.4.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

## Basic Array Creation

In [2]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
a = [1,2,3,4]
a

[1, 2, 3, 4]

In [4]:
np.array(a)

array([1, 2, 3, 4])

In [7]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Array generation function

In [9]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [13]:
arr = np.zeros(4)
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
arr = np.ones(4)
arr = np.ones((4,8))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [19]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

## Random Generation Function

In [21]:
np.random.rand(10)

array([0.07081137, 0.15947092, 0.86189089, 0.76503214, 0.63867674,
       0.49456494, 0.01584051, 0.16282127, 0.02665209, 0.54444687])

In [22]:
np.random.randn(10)

array([ 1.12291435,  0.09829377, -0.62891875, -0.64704976,  0.54060258,
       -0.51427719,  0.69573146, -0.39499492, -0.44302563,  0.27994529])

In [23]:
np.random.randint(10,20,10)

array([10, 10, 13, 19, 13, 18, 11, 18, 13, 13])

## Array Attributes

In [24]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
arr.shape

(3, 3)

In [26]:
arr.size

9

In [27]:
arr.dtype

dtype('int64')

## Array Methods

In [28]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
arr.min()

np.int64(1)

In [30]:
arr.max()

np.int64(9)

In [31]:
arr.sum()

np.int64(45)

In [32]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [34]:
np.sum(arr, axis=0)

array([12, 15, 18])

In [35]:
arr.mean()

np.float64(5.0)

In [36]:
arr.std()

np.float64(2.581988897471611)

In [37]:
arr.argmax()

np.int64(8)

In [38]:
arr.argmin()

np.int64(0)

## Reshaping and Resizing

In [39]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [40]:
arr = arr.reshape(6,5)

In [41]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])