### Valid Sudoku

In [91]:
import numpy as np

In [92]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [93]:
l = np.sum(s, axis=0) 
for i in l:
    if i != 45:
        print('for rows, sudoku is not valid!')
        break
else:
    print('for rows, sudoku is valid!')

for rows, sudoku is valid!


In [94]:
l = np.sum(s, axis=1) 
for i in l:
    if i != 45:
        print('for columns, sudoku is not valid!')
        break
else:
    print('for columns, sudoku is valid!')

for columns, sudoku is valid!


In [95]:
# Check 3x3 subgrids
valid = True

for i in range(0, 9, 3):        # row blocks
    for j in range(0, 9, 3):    # column blocks
        subgrid = s[i:i+3, j:j+3]
        print(subgrid)
        if np.sum(subgrid) != 45:
            print("3x3 grid is not valid!")
            valid = False
            break
    if not valid:
        break

if valid:
    print("3x3 grid is valid!")

[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]
3x3 grid is valid!


### General Questions

In [96]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [97]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [98]:
#Find the average age of students.
data[:,0].mean()

np.float64(18.4)

In [99]:
#Extract Math marks of all students.
maths = data[:,1]

In [100]:
#Find the highest Science mark.
data[:,2].max()

np.int64(95)

In [101]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1] > 90]

array([[19, 92, 88]])

In [102]:
#Increase Math marks of all students by 5.
data[:,1] = data[:,1] + 5

In [103]:
data[:,1]

array([90, 97, 81, 70, 95])

In [104]:
#Find how many students are younger than 19.
data[data[:,0] < 19].shape[0]

3

In [105]:
#Calculate the average marks in each subject (column-wise mean).
data[:,1].mean()

np.float64(86.6)

In [106]:
data[:,2].mean()

np.float64(83.2)

In [107]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [109]:
#Replace all Science marks < 75 with 0.
data[data[:,2] < 75, 2] = 0

In [110]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])