In [1]:
import numpy as np

In [2]:
lst = [1,2,3]
arr = np.array([1,2,3])

In [5]:
type(lst)

list

In [6]:
type(arr)

numpy.ndarray

In [7]:
a = np.array([1,2,3,4])

In [8]:
a

array([1, 2, 3, 4])

In [9]:
a.shape

(4,)

In [10]:
a.size

4

In [11]:
a.ndim

1

In [12]:
a.dtype

dtype('int64')

In [13]:
# Array Creation
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [14]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
np.full((2,2), 10)

array([[10, 10],
       [10, 10]])

In [17]:
np.empty((2,2))

array([[9.00815070e-319, 0.00000000e+000],
       [3.68699547e-315, 3.68699587e-315]])

In [19]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [20]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.random.rand(3,3)

array([[0.00314447, 0.59807328, 0.73084366],
       [0.20602008, 0.82047436, 0.5044377 ],
       [0.68221693, 0.94263197, 0.17906599]])

In [23]:
np.random.randint(1,10,(2,2))

array([[8, 7],
       [8, 2]])

In [24]:
# Array Indexing and Slicing

a = np.array([10,20,30,40])
a[0]
a[2]

30

In [25]:
a[-1]

40

In [26]:
a[1:4]

array([20, 30, 40])

In [27]:
a[:3]

array([10, 20, 30])

In [28]:
a[2:]

array([30, 40])

In [29]:
arr = np.array([[1,2],
               [3,4]])
arr[0,1]

2

In [30]:
a[a>20]

array([30, 40])

In [31]:
a[[0,2,3]]

array([10, 30, 40])

In [35]:
# Array Manipulation
a = a.reshape(2,2)

In [37]:
a.flatten()

array([10, 20, 30, 40])

In [38]:
a.ravel()

array([10, 20, 30, 40])

In [39]:
a.T

array([[10, 30],
       [20, 40]])

In [41]:
np.transpose(a)

array([[10, 30],
       [20, 40]])

In [42]:
np.resize(a, (3,4))

array([[10, 20, 30, 40],
       [10, 20, 30, 40],
       [10, 20, 30, 40]])

In [43]:
np.insert(a,1,99)

array([10, 99, 20, 30, 40])

In [44]:
np.delete(a,2)

array([10, 20, 40])

In [45]:
np.append(a,100)

array([ 10,  20,  30,  40, 100])

In [46]:
# Mathematical Operations

In [47]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [48]:
a+b

array([ 6,  8, 10, 12])

In [49]:
a-b

array([-4, -4, -4, -4])

In [50]:
a*b

array([ 5, 12, 21, 32])

In [51]:
a/b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [52]:
a+10

array([11, 12, 13, 14])

In [53]:
a*2

array([2, 4, 6, 8])

In [54]:
a>5

array([False, False, False, False])

In [55]:
a == 3

array([False, False,  True, False])

In [56]:
np.logical_and(a>2, a<8)

array([False, False,  True,  True])

In [57]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [58]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [59]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [60]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [61]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [62]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [63]:
np.abs(a)

array([1, 2, 3, 4])

In [64]:
np.round(a)

array([1, 2, 3, 4])

In [65]:
# BroadCasting
a + 10

array([11, 12, 13, 14])

In [66]:
a

array([1, 2, 3, 4])

In [67]:
A = np.array([[1],[2],[3]])
B = np.array([10,20,30])
A+B

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

In [68]:
# Aggregation functions

In [69]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [70]:
np.sum(a)

10

In [71]:
np.mean(a)

2.5

In [72]:
np.median(a)

2.5

In [73]:
np.std(a)

1.118033988749895

In [74]:
np.var(a)

1.25

In [75]:
np.min(a)

1

In [76]:
np.max(a)

4

In [77]:
np.argmax(a)

3

In [78]:
np.argmin(a)

0

In [79]:
np.sum(a, axis=0)

10

In [83]:
a = np.array([[1,2,3,4],
             [5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [84]:
np.sum(a, axis=0)

array([ 6,  8, 10, 12])

In [85]:
np.sum(a, axis=1)

array([10, 26])

In [86]:
# Statistical Operations

In [87]:
data = np.array([1,2,3,4,5])

In [88]:
data

array([1, 2, 3, 4, 5])

In [89]:
np.mean(data)

3.0

In [90]:
np.median(data)

3.0

In [91]:
from scipy.stats import mode

In [92]:
mode(data)

ModeResult(mode=1, count=1)

In [93]:
np.var(data)

2.0

In [94]:
np.std(data)

1.4142135623730951

In [95]:
np.percentile(data, 50)

3.0

In [97]:
np.quantile(data,0.75)

4.0

In [99]:
# np.corrcoef(x,y)
# np.cov(x,y)

In [100]:
# Random Module
np.random.rand()

0.9929752746764152

In [102]:
np.random.randint(1,100)

23

In [103]:
np.random.sample(5)

array([0.95935693, 0.19919229, 0.54536446, 0.1973499 , 0.02919009])

In [104]:
np.random.choice([1,2,3,4], size=3)

array([4, 4, 1])

In [105]:
np.random.shuffle(a)

In [106]:
np.random.seed(42)

In [107]:
np.random.normal(
    loc=0,
    scale=1,
    size=1000
)

array([ 4.96714153e-01, -1.38264301e-01,  6.47688538e-01,  1.52302986e+00,
       -2.34153375e-01, -2.34136957e-01,  1.57921282e+00,  7.67434729e-01,
       -4.69474386e-01,  5.42560044e-01, -4.63417693e-01, -4.65729754e-01,
        2.41962272e-01, -1.91328024e+00, -1.72491783e+00, -5.62287529e-01,
       -1.01283112e+00,  3.14247333e-01, -9.08024076e-01, -1.41230370e+00,
        1.46564877e+00, -2.25776300e-01,  6.75282047e-02, -1.42474819e+00,
       -5.44382725e-01,  1.10922590e-01, -1.15099358e+00,  3.75698018e-01,
       -6.00638690e-01, -2.91693750e-01, -6.01706612e-01,  1.85227818e+00,
       -1.34972247e-02, -1.05771093e+00,  8.22544912e-01, -1.22084365e+00,
        2.08863595e-01, -1.95967012e+00, -1.32818605e+00,  1.96861236e-01,
        7.38466580e-01,  1.71368281e-01, -1.15648282e-01, -3.01103696e-01,
       -1.47852199e+00, -7.19844208e-01, -4.60638771e-01,  1.05712223e+00,
        3.43618290e-01, -1.76304016e+00,  3.24083969e-01, -3.85082280e-01,
       -6.76922000e-01,  

In [108]:
# Sorting
a = np.array([1,5,2,3,10,40,20,11])
a

array([ 1,  5,  2,  3, 10, 40, 20, 11])

In [109]:
np.sort(a)

array([ 1,  2,  3,  5, 10, 11, 20, 40])

In [110]:
np.argsort(a)

array([0, 2, 3, 1, 4, 7, 6, 5])

In [111]:
np.where(a>5)

(array([4, 5, 6, 7]),)

In [112]:
np.unique(a)

array([ 1,  2,  3,  5, 10, 11, 20, 40])

In [113]:
a[a>5]

array([10, 40, 20, 11])

In [114]:
np.where(a>5, "Yes", "No")

array(['No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes'], dtype='<U3')

In [115]:
# Combining and Splitting Array

In [116]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [117]:
a

array([1, 2, 3, 4])

In [118]:
b

array([5, 6, 7, 8])

In [119]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [120]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [121]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [122]:
np.split(a,2)

[array([1, 2]), array([3, 4])]

In [123]:
# Handling Missing Values

In [124]:
np.nan

nan

In [125]:
a = np.array([1,2,3,np.nan,4,5,np.nan])

In [126]:
a

array([ 1.,  2.,  3., nan,  4.,  5., nan])

In [127]:
np.isnan(a)

array([False, False, False,  True, False, False,  True])

In [128]:
a[np.isnan(a)==False]

array([1., 2., 3., 4., 5.])

In [129]:
np.nanmean(a)

3.0

In [130]:
np.nansum(a)

15.0

In [131]:
np.nanmax(a)

5.0

In [132]:
np.nanmin(a)

1.0

In [133]:
# Linear Algebra

In [134]:
v = np.array([1,2,3])

In [135]:
v

array([1, 2, 3])

In [136]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [138]:
B = np.array([[5,6],[7,8]])
B

array([[5, 6],
       [7, 8]])

In [139]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [140]:
A @ B # np.matmul(A,B)

array([[19, 22],
       [43, 50]])

In [141]:
np.linalg.det(A)

-2.0000000000000004

In [142]:
np.linalg.det(B)

-2.000000000000005

In [143]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [144]:
np.linalg.eig(A)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [146]:
# Solve Linear Equation
A = np.array([[2,1],
             [1,3]])
B = np.array([8,13])
np.linalg.solve(A,B)

array([2.2, 3.6])

In [147]:
# File Operations

In [148]:
a = np.array([1,2,3,4,5,6,7])

In [149]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [150]:
np.save("data.npy", a)

In [151]:
np.load("data.npy")

array([1, 2, 3, 4, 5, 6, 7])

In [152]:
np.savetxt("data.txt", a)

In [153]:
np.loadtxt("data.txt")

array([1., 2., 3., 4., 5., 6., 7.])

In [154]:
# Real Data Analysis Practice

In [155]:
# 1) Student Marks Analysis

In [156]:
marks = np.array([78,65,89,90,45])
marks

array([78, 65, 89, 90, 45])

In [157]:
np.mean(marks)

73.4

In [158]:
np.max(marks)

90

In [159]:
np.min(marks)

45

In [160]:
# Sales Analysis
sales = np.array([1000,1200,900,1500])
sales.sum()
sales.mean()

1150.0

In [161]:
# Weather Analysis
temp = np.array([32,34,30,29,35])
np.mean(temp)
np.std(temp)

2.280350850198276

In [162]:
# Dataset Cleaning
data = np.array([10,20,np.nan,30])
np.nanmean(data)

20.0

In [164]:
# Statistical Summary
data = np.array([1,2,3,4,5,6,7])
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Std:", np.std(data))
print("Min:", np.min(data))
print("Max:", np.max(data))

Mean: 4.0
Median: 4.0
Std: 2.0
Min: 1
Max: 7


## General Questions 

In [165]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [166]:
data.shape #Get the shape of the matrix.

(5, 3)

In [172]:
#Find the average age of students.
np.mean(data, axis=0)[0]

18.4

In [176]:
#Extract Math marks of all students.
data[:,1]

array([85, 92, 76, 65, 90])

In [177]:
#Find the highest Science mark.
data[:,2].max()

95

In [180]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1] > 90]

array([[19, 92, 88]])

In [182]:
#Increase Math marks of all students by 5.
data[:,1] = data[:,1] + 5

In [183]:
data[:,1]

array([90, 97, 81, 70, 95])

In [187]:
#Find how many students are younger than 19.
data[data[:,0] < 19].shape[0]

3

In [191]:
#Calculate the average marks in each subject (column-wise mean).
data[:,1:]

array([[90, 78],
       [97, 88],
       [81, 95],
       [70, 70],
       [95, 85]])

In [193]:
np.mean(data[:,1:], axis=0)

array([86.6, 83.2])

In [195]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [206]:
#Replace all Science marks < 75 with 0.
data[data[:,2] < 75,2] = 0

In [207]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])